name: owl
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy
  - pandas
  - imutils
  - tqdm
  - python-dateutil
  - pytz
  - six
  - wcwidth
  - pip
  - pip:
      - blessed==1.20.0
      - colorzero==2.0
      - glob2==0.7
      - gpiozero==1.6.2
      - opencv-contrib-python
