jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Auto comment on issue
      uses: actions/github-script@v0.9.0
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        script: |
          const openai = require('openai-api');
          const OPENAI_API_KEY = process.env.OPENAI_API_KEY;
          const openaiInstance = new openai(OPENAI_API_KEY);

          const issueTitle = context.payload.issue.title;
          const issueBody = context.payload.issue.body;
          const prompt = `Title: ${issueTitle}\nBody: ${issueBody}\n\nPlease provide a helpful comment:`;

          (async () => {
            const gptResponse = await openaiInstance.complete({
              engine: 'davinci',
              prompt: prompt,
              maxTokens: 350,  // Increased token limit for more detailed responses
              temperature: 0,
              topP: 1,
              frequencyPenalty: 0,
              presencePenalty: 0
            });

            const comment = gptResponse.data.choices[0].text.trim();
            const issue_number = context.payload.issue.number;
            const githubToken = process.env.GITHUB_TOKEN;
            const octokit = new github.GitHub(githubToken);

            await octokit.issues.createComment({
              ...context.repo,
              issue_number: issue_number,
              body: comment
            });
          })();