- name: Label Issue Based on Analysis
  env:
    GITHUB_TOKEN: ${{ secrets.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 }}
  run: |
    python -c "
from github import Github
import os

github_token = os.getenv('GITHUB_TOKEN')
repo_name = os.getenv('GITHUB_REPOSITORY')
issue_number = os.getenv('ISSUE_NUMBER')
g = Github(github_token)
repo = g.get_repo(repo_name)
issue = repo.get_issue(int(issue_number))

# Example: If 'bug' is in the analysis, label it as a bug
if 'bug' in '${{ steps.analyze_issue.outputs.analysis_result }}':
    issue.add_to_labels('bug')
elif 'enhancement' in '${{ steps.analyze_issue.outputs.analysis_result }}':
    issue.add_to_labels('enhancement')
else:
    issue.add_to_labels('needs investigation')
"
