name: Python RaspberryPi with ChatGPT Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install jq
        run: sudo apt-get install jq

      - name: Generate requirements.txt using GPT
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          # Extract relevant project files to send to GPT for generating requirements.txt
          FILE_LIST=$(find . -type f -name "*.py" -print0 | xargs -0 cat 2>/dev/null || true)

          # Check if FILE_LIST is empty
          if [ -z "$FILE_LIST" ]; then
            echo "No Python files found for generating requirements.txt."
            exit 1
          fi

          # Send a request to GPT to generate a requirements.txt file
          REQUIREMENTS=$(curl -s -X POST https://api.openai.com/v1/chat/completions \
          -H "Authorization: Bearer $OPENAI_API_KEY" \
          -H "Content-Type: application/json" \
          -d '{
            "model": "gpt-4",
            "messages": [{"role": "user", "content": "Based on the following Python project files, provide a requirements.txt for this project:\n'"$FILE_LIST"'"}]
          }' | jq -r '.choices[0].message.content')

          # Save the generated requirements to a file
          echo "$REQUIREMENTS" > requirements.txt
          
          # Display the generated requirements for verification
          echo "Generated requirements.txt:"
          cat requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests on Raspberry Pi emulator
        run: |
          # Check if the 'tests' directory exists
          if [ ! -d "tests" ]; then
            echo "'tests' directory does not exist. Creating 'tests' directory."
            mkdir tests
          fi

          # Example of running tests on a Raspberry Pi emulator
          python -m unittest discover tests/ || TEST_FAILED=true

      - name: Handle Test Failures with ChatGPT
        if: failure() # Run this step if the previous step failed
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          echo "Test failures detected. Sending error log to ChatGPT for suggestions..."
          
          # Capture the error log
          ERROR_LOG=$(cat /home/runner/work/_temp/_stderr)  # Adjust the path to where error logs are stored

          # Send the error log to ChatGPT for suggestions
          RESPONSE=$(curl -s -X POST https://api.openai.com/v1/chat/completions \
          -H "Authorization: Bearer $OPENAI_API_KEY" \
          -H "Content-Type: application/json" \
          -d '{
            "model": "gpt-4",
            "messages": [{"role": "user", "content": "The following error was found during testing:\n'"$ERROR_LOG"'\nPlease provide the exact code changes needed to fix the error in a structured JSON format."}]
          }' | jq -r '.choices[0].message.content')

          # Check if RESPONSE is not empty
          if [ -z "$RESPONSE" ]; then
            echo "No suggestion from ChatGPT. Skipping code changes."
            exit 1
          else
            echo "Suggestion from ChatGPT: $RESPONSE"
          fi

          # Save the response to a file
          echo "$RESPONSE" > suggested_changes.json

          # Use a Python script to parse the JSON and apply the changes
          python apply_changes.py suggested_changes.json

          # Show the diff for verification
          git diff

      - name: Commit and Push Fixes
        if: success() # Run this step if changes were applied
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Apply ChatGPT suggested fixes"
          git push https://x-access-token:${GH_TOKEN}@github.com/bassyboi/OpenWeedLocator--beta2.git HEAD:main

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Raspberry Pi
        run: |
          ssh pi@<raspberry_pi_ip> 'bash -s' < deploy.sh
