name: Python RaspberryPi with ChatGPT Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install jq
        run: sudo apt-get install jq

      - name: Generate requirements.txt using GPT
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          # Extract relevant project files to send to GPT for generating requirements.txt
          FILE_LIST=$(find . -name "*.py" | xargs cat)

          # Send a request to GPT to generate a requirements.txt file
          REQUIREMENTS=$(curl -s -X POST https://api.openai.com/v1/chat/completions \
          -H "Authorization: Bearer $OPENAI_API_KEY" \
          -H "Content-Type: application/json" \
          -d '{
            "model": "gpt-4",
            "messages": [{"role": "user", "content": "Based on the following Python project files, provide a requirements.txt for this project:\n'"$FILE_LIST"'"}]
          }' | jq -r '.choices[0].message.content')

          # Save the generated requirements to a file
          echo "$REQUIREMENTS" > requirements.txt
          
          # Display the generated requirements for verification
          echo "Generated requirements.txt:"
          cat requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests on Raspberry Pi emulator
        run: |
          # Example of running tests on a Raspberry Pi emulator
          # You can use QEMU or a Docker container that emulates Raspberry Pi architecture
          # Replace this command with the appropriate emulator test command
          python -m unittest discover tests/ || echo "Tests failed, moving to ChatGPT analysis."

      - name: Save Test Output
        if: failure() # Run this step only if the previous step fails
        run: |
          # Save test output to a file for analysis
          mkdir -p logs
          python -m unittest discover tests/ > logs/test_output.log 2>&1 || true

      - name: Check for errors and interact with ChatGPT API
        if: failure() # Run this step only if the previous step fails
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          # Extract the error logs
          ERROR_LOG=$(tail -n 50 logs/test_output.log) # Adjust the number of lines as needed
          
          # Send errors to ChatGPT and get suggestions
          RESPONSE=$(curl -s -X POST https://api.openai.com/v1/chat/completions \
          -H "Authorization: Bearer $OPENAI_API_KEY" \
          -H "Content-Type: application/json" \
          -d '{
            "model": "gpt-4",
            "messages": [{"role": "user", "content": "The following error was found during testing:\n'"$ERROR_LOG"'\nPlease provide the exact code changes needed to fix the error in a structured JSON format."}]
          }' | jq -r '.choices[0].message.content')
          
          # Check if RESPONSE is not empty
          if [ -z "$RESPONSE" ]; then
            echo "No suggestion from ChatGPT. Skipping code changes."
            exit 1
          else
            echo "Suggestion from ChatGPT: $RESPONSE"
          fi

      - name: Apply suggested code changes
        if: success() # Run this step only if ChatGPT provided a suggestion
        run: |
          # Save the response to a file
          echo "$RESPONSE" > suggested_changes.json
          
          # Use a Python script to parse the JSON and apply the changes
          python apply_changes.py suggested_changes.json
          
          # Show the diff for verification
          git diff

      - name: Commit and Push Fixes
        if: success() # Run this step if changes were applied
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Apply ChatGPT suggested fixes"
          git push https://x-access-token:${GH_TOKEN}@github.com/bassyboi/OpenWeedLocator--beta2.git HEAD:main

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Raspberry Pi
        run: |
          # Deploy the updated code to a remote Raspberry Pi
          # Use SSH or any deployment tool like Ansible
          echo "Deploying to Raspberry Pi..."
          ssh pi@<raspberry_pi_ip> 'bash -s' < deploy.sh